### ISSUE TITLE
recupero: lista de facturas

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#103]
El estado actual del proceso de facturación es inconpleto. Para poder facturar es necesario poder presentar lo que se llama _Anexo II_. Este formulario es obligatorio y esta cubierto por una [librería nuestra que tambien es abierta](https://github.com/cluster311/Anexo2) (hacer un análisis rápido de esta librería para entender su funcionalidad).

El botón _Factura_ (Debería llamarse _Anexo II_) de la [lista de facturas](http://localhost:8000/recupero/facturacion/) genera este formulario. 

![image](https://user-images.githubusercontent.com/3237309/82770321-81a49880-9e0e-11ea-87d9-249e1138c23b.png)

[La vista Anexo2View](https://github.com/cluster311/ggg/blob/develop/recupero/views_anexo2.py#L9:L9) intenta cargar los datos necesarios para generarla. Esta vista depende de otras y está incompleta. [Requiere más datos](https://github.com/cluster311/ggg/blob/develop/recupero/models.py#L191), estos deberán ser cubiertos en nuevos issues.
Analizar si #187 describe el problema que tenemos y si es útil como issue.

Finalmente, cuando el operario quiera imprimir el Anexo II debe ser:
 - Bloqueado cuando haya datos insuficientes que son obligatorios (consultas incompletas). 
 - Permitirle ver el formulario pero alertado cuando haya datos no obligatorios que podrían agregarse
 - Permitir acceso sin alertas cuando todo estè en condiciones.
Estos deben ser explicados claramente para lo que se requiere documetar un nuevo issue.

**Tareas**
 - [x] Renombrar el boton _Factura_ a _Anexo II_
 - [x] Agregar un issue por cada problema en la obtención de datos para la factura que no esté resuleta (hoy parchamos e inventamos datos porque no está definido como obtenerlos)
 - [ ] Despues de describir los problemas con los datos necesarios, **crear un nuevo issue** documentando los requisitos necesarios para bloquear, permitir con o sin alertas generar e imprimir el anexo II.

**Comment by marcorichetta** [comment]
@avdata99 Este issue se podría cerrar o falta algo?
