### ISSUE TITLE
Filtro en vista de turnos

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#104]
Cuando se definen los turnos de varias especialidad el calendario empieza a ser dificil de mirar
 - [x] Agregar filtro por especialidad
 - [x] Agregar filtro por centro de salud (quizás que de manera predeterminada solo se vean los turnos del centro de salud del selector que ya existe)

**Comment by marcorichetta** [comment]
Se podría usar el mismo selector de Especialidad que se usa en la vista para **agendar** turnos.
