### ISSUE TITLE
Asignación de turnos manual

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#106]
Asegurarse que las personas que van a los centros de salud sin previo turno pueden ser asignadas a un turno aún no teniendo usuario en el sistema.
 - [x] Si no existe crear un permiso para _asignar turno a paciente solo con su nro de DNI y nombre_. Los usuarios que definen los turnos masivamente no son los mismo que atienden en mesa de entrada
 - [x] Los usuario con este permiso deben tener visible una opción en el menú que diga _turnos del día_ que les habilita una vista solo del día con los turnos.
 - [x] Disponer un menú como en #30 (quizás el mismo) con las opciones de este usuario: pro lo pronto: _asignar a paciente_. Aquí (por ahora) debe pedirse solo el DNI
 - [x] Permitir la carga rápida del paciente. Si ya existe, ok, Si no, traer los datos del paciente vía [PUCO/SISA o SISA/ReNaPer](https://pypi.org/project/sisa/). Ver [ejemplo en el código](https://github.com/cluster311/ggg/blob/master/pacientes/models.py#L167). Avisar cuando se llegue acá para que el equipo del gobierno que tiene las credenciales, lo pruebe. 
 - [ ] Si el paciente es nuevo o si no tiene _CarpetaFamiliar_ definida permitir mostrar el formulario de #114. Mostrar un alerta o aviso si es paciente y no tiene carpeta familiar.

**Comment by alantoris** [comment]
Resta validar los resultado de PUCO/SISA y agregar la parte de CarpetaFamiliar cuando #114 este listo
