### ISSUE TITLE
Revisar la grabacion de medidas anexas

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#120]
La forma actual de [mostrar](https://github.com/cluster311/ggg/blob/fb1387c67256097a1624ebdc0bbfc9d4da876a87/pacientes/templates/pacientes/evolucion.html#L38-L51) y de [grabar](https://github.com/cluster311/ggg/blob/fb1387c67256097a1624ebdc0bbfc9d4da876a87/pacientes/views.py#L134-L141) los datos de las medidas anexas a las consultas posiblemente no sea la mejor

Revisarla, no aplica literalmente el concepto de formset aunque se le parece. Las medidas anexas cambian segun la especialidad de la consulta

**Comment by mgaitan** [comment]
no estoy seguro de entender esto @avdata99 .

 cual es el tema? el form deberia pedir distintos datos dependiendo la especialidad? eso se puede saber de antemano o debe ser "configurable"  ?

que tal, para simplificar, definir una "plantilla" que predefina parte del texto libre?

**Comment by avdata99** [comment]
Dependiendo de la especialidad hay que pedir diferentes _medidas_  @mgaitan.
Son obligatorias o no segun la especialidad. Esta ya es configurable ahora.
![image](https://user-images.githubusercontent.com/3237309/69503673-f1d36f80-0efa-11ea-93e8-841995997fda.png)

No entiendo lo de _texto libre_ porque en este caso son siempre números.
