### ISSUE TITLE
Turno CANCELADO debería poder asignarse y no confirmarse

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#124]
![image](https://user-images.githubusercontent.com/3237309/69084988-15427a00-0a24-11ea-9119-6e7e66df155b.png)

Turnos en estado CANCELADO debe mostrar solo la opción asignar. No mostrar los botones _confirmar_ o _cancelar_

Verificar los permisos de asignar turnos del usuario

**Comment by alantoris** [comment]
Creo que el boton Confirmar ahi esta deshabilitado (tal vez no se note tanto por el color). Como no esta mas Asignado, no se puede confirmar.

Para Asignarlo a un paciente nuevo existen dos opciones, o que el Paciente vaya a la solpa de 'Agendar Turno' o el administrativo lo haga desde 'Gestionar Turnos' en la cual asigna los turnos del dia con el DNI. Aunque no estoy seguro si esas vistas traen turnos cancelados o solo los disponibles (en cuanto pueda lo reviso)

Desde esta pantalla un administrativo tambien deberia poder asignar un turno?

**Comment by avdata99** [comment]
No es urgente este ticket, fijate el Milestone.
Es para revisar. Yo esperaba ver la posibilidad de asignarlo ya que tenicamente esta disponible
Pero no hay apuro con esto
