### ISSUE TITLE
Testing de vistas

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#145]
Hacer tests para cada vista
 - [ ] Que falle cuando un usuario no logueado intenta acceder a una vista que requiera usuario con permisos (quizás que el `raise_exception = True` esté solo en el test y no en la vista)
 - [ ] Si la vista es exclusiva de un perfil (Administrativo / Profesional / Ciudadano) que falle con los perfiles que no corresponde.

Comenzado [aquí](https://github.com/cluster311/ggg/blob/master/profesionales/tests.py). Seguir por este camino y mejorarlo si hay una mejor forma de hacerlo.

Despues de cada push y vía [Travis](https://github.com/cluster311/ggg/blob/master/.travis.yml) se puede [chequear online que pasen todos los tests](https://travis-ci.org/cluster311/ggg) de la app. Es una nueva práctica a tener.

**Comment by avdata99** [comment]
Comenzado [aquí](https://github.com/cluster311/ggg/blob/master/profesionales/tests.py). Seguir por este camino y mejorarlo si hay una mejor forma de hacerlo

**Comment by avdata99** [comment]
@marcorichetta el PR #172 ya se mezclo a develop.
Como parte de tu review necesito que revises que los checks de este issue esten funcionando en develop.
Si ves todo bien podes cerrar el issue, de no ser así agrega tus notas aquí y reabrilo porfavor.

**Comment by marcorichetta** [comment]
> Que falle cuando un usuario no logueado intenta acceder a una vista que requiera usuario con permisos

- Algunas vistas como las de `/turnos` o /`profesionales` tiran una exception 403.
- `/obras-sociales/lista.html` redirige al login.

Cómo sabemos que si redirigir o no?

**Comment by avdata99** [comment]
> > Que falle cuando un usuario no logueado intenta acceder a una vista que requiera usuario con permisos
> 
> * Algunas vistas como las de `/turnos` o /`profesionales` tiran una exception 403.
> * `/obras-sociales/lista.html` redirige al login.
Ok, revisa entonces esta vista y fijate si faltan otras @ramosfm 

> Cómo sabemos que si redirigir o no?

**Muy buena pregunta**. Podemos poner que la excepiòn del decorador se active solo en los tests?
Quizás cuando un usuario quiera ir a un link que guardo, el espera que se lo redirija al login y no ver un error 403 que no entienda.
Fijate Facu si podemos hacer que el `raise_exception = True` solo se use en los tests y no en las vistas. Creo que esta sería la solución. Creo que si vamos a querer el redirect.
Tambien podes proponer otra solución
 
> > Asegurarse que cada vista tenga un DocString que indique hace y que perfiles deben verlo
> 
> Esto debería convertirse en un issue aparte si hay que aplicarlo en todas las vistas del sistema.

En caso de que @ramosfm no esté ya con esto, creá un nuevo issue @marcorichetta y tomalo vos aparte.

**Comment by ramosfm** [comment]
bien dale mañana lo veo, yo habia entendido de ponerlo en todos lados, teniendo en cuenta lo de las funciones de calendario por eso lo desarrolle asi, pero mañana lo veo. Mi idea es que dejaramos como una base para los test por eso hice todo sobre profesionales, asi despues los demas salen mas rapido. las raise exception los veo mañana y a la tarde lo hablamos si encuentro algo.

**Comment by avdata99** [comment]
Perfecto facu. Efectivamente.hubo un cambio de planes por esto de que vamos a esperar el redirect al login. Pensé que podíamos sacarlo pero pensándolo mejor perdemos mucho si lo sacamos. 
Pero en los test si necesitamos tener claro que falla
