### ISSUE TITLE
Revisar URLs

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#175]
Error detectado: Se puede acceder a **/turnos/gestionar_turnos/asd** que no existe

Al parecer algunas URLs no están bien definidas. Por ejemplo, la [URL del error](https://github.com/cluster311/ggg/blob/develop/calendario/urls.py#L18).
El error es que no tiene el **$** al final indicando que la URL termina.

 - [x] Confirmar que es eso corrigiendo la URL
 - [x] Corregir esa URL y todas las del sistema que estén mal

**Comment by marcorichetta** [comment]
El template [consulta_listview.html](https://github.com/cluster311/ggg/blob/a9d808408222ae326bde61d8ae8e2cf091415950/pacientes/templates/pacientes/consulta_listview.html#L11) muestra mensajes de inicio o cierre de sesión.

**URL:** `localhost:8000/pacientes/1/historia` donde 1 es el DNI
![imagen](https://user-images.githubusercontent.com/19599150/80557116-38e2f680-89ac-11ea-8c8e-54282f654981.png)

- Me parece que podría eliminar esas líneas ya que es el único template que muestra esos mensajes. Además es información irrelevante para esa página.
