### ISSUE TITLE
Cargar Obra Social del paciente cuando se agenda un turno

### ISSUE THREAD

**Issue by marcorichetta** [cluster311/ggg#248]
Se debería poder cargar o elegir la obra social con la que se atiende el paciente cuando se agenda el turno.

**Solucion propuesta**
- Cuando se ingresa el DNI del paciente se debe poder elegir la entre las OS disponibles de dicho paciente. (Usar función Facu #269)
- Si el paciente no existe se debería crear el mismo y elegir su OS.

**Tareas**
 - [x] Agregar select de OS cuando se agenda el turno
 - [x] Agregar la obra social en el modelo Turno y Consulta.
 - [x] Actualizar el Turno y la Consulta con la OS elegida por el usuario.

**Tests**
 - [x] Cuando se agenda el Turno se crea una consulta que debe tener asignada la Obra Social elegida.

**Comment by ramosfm** [comment]
creo que este issue queda pendiente porque si vamos a hacer que al poner DNI, traiga de cualquier otro sistema los datos del paciente. O al menos que sigamos evaluando alguna carga completa manual en caso de que no este en ningún sistema

**Comment by marcorichetta** [comment]
Claro. Creo que con lo que hablamos la semana pasada este issue no aplicaría.
Estaría bueno tener una prueba trayendo la información de los demás sistemas así sabemos como seguir con esto.
