### ISSUE TITLE
[BUG] Anexo 2 debe interceptar errores

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#258]
**Descripcion del bug**
Todavía hay errores no interceptados al tratar de ver anexo II
URL del error: `/recupero/anexo-II/NN`
Screenshot:
![image](https://user-images.githubusercontent.com/3237309/87730697-f0fb9080-c79e-11ea-8fbf-4bc55e326649.png)

**Como reproducir el error**
Desde una factura incompleta trato de generar el anexo II

**Solucion esperada**
 - [x] Interceptar los llamadas a imprimir el anexo II

**Tests**
 - [x] Test de intentos de imprimir anexo II para facturas incompletas de multiples formas diferentes
 - [x] Test de acceso a la vista de anexo II desde usuarios anónimos o con otros roles que no sean de recupero

**Importante**
Puede que esto vaya en issue aparte

- [x] Actualizar versión de librería Anexo2 => 0.107
- [ ] Sacar valores hardcodeados `tipo de beneficiario` y `parentesco` #251
- [x] Obtener datos de la OS del paciente a partir de la factura

https://stackoverflow.com/questions/5255657/how-can-i-disable-logging-while-running-unit-tests-in-python-django

**Comment by marcorichetta** [comment]
Me auto asigno este issue ya que estuve tocando todo lo relacionado a la generación del Anexo2

**Comment by marcorichetta** [comment]
![imagen](https://user-images.githubusercontent.com/19599150/88989343-c1c24480-d2b1-11ea-841f-4093b7e5a528.png)

Falta buscar forma de diferenciar entre
- Errores **dentro de una sección** (Ejemplo sección **atención**)
- Error cuando la sección en `None` (Ejemplo sección **hospital**)
