### ISSUE TITLE
Implementar django-autocomplete-light para cie10

### ISSUE THREAD

**Issue by mgaitan** [cluster311/ggg#26]
necesitamos declarar los autocomplete para el m2m de cie10 (codigos de diagnostico)

https://django-autocomplete-light.readthedocs.io/en/master/

depende de #25

**Comment by wilmays10** [comment]
Yo me puedo encargar de esto @mgaitan

**Comment by mgaitan** [comment]
avanti, acordate de 25 tambien.

**Comment by wilmays10** [comment]
#25 está listo para [mergear](https://github.com/cluster311/ggg/pull/32)
