### ISSUE TITLE
Paciente x DNI al buscar

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#262]
Al ingresar un paciente en una factura de recupero debería poder ponerse solo el DNI.

Yo en este punto no se si el paciente esta o no en el sistema. 
Solo con poner un DNI el sistema debería ser inteligente y hacer esa busqueda por mi
 - [x] Crear un nuevo issue para cargar los datos de SSS en el sistema

Solo poner el DNI (quizas hasta no permitir la busqueda por nombre que puede ser pesada) debería suficiente.
Quizás el select2 actual requiera bastantes cambios

Campo DNI:
 - [x] Ocultar el campo de django: Foreign Key PACIENTE
 - [x] Dejar solo un campo de texto y el boton + desaparece y se transforma en una lupita
   + [x] Limpiar espacios, puntos y todo lo demas antes de hacer el el query (las consultas serás caras)
 - [x] Si el DNI existe en nuestra base, listo. Se deshabilita la caja de texto de DNI y se muestra el nombre y apelldo
 - [x] Si el DNI no existe se busca en PUCO y si no existe se avisa y se abre el formulario que ya creamos para agregar un paciente.
 - [x] En ambos casos mostrar un loading mientras buscamos en la base o en PUCO
 - [x] En ambos casos cargar la lista de OSS con las que tengamos (en la base en PUCO) y el boton [+] de la OSS la agrega a la tabla obreasocial-paciente
 - [x] Revisar el tipo de prestacion, esperamos un select2
 - [ ] Si se puede: agregar un boton guardar + Abrir Anexo II. Si no es facil al menos asegurarse que la factura recien creada esta bien visible en la lista

**Comment by ramosfm** [comment]
algo que se me ocurre desde el autocomplete podríamos hacer lo siguiente, seguir buscando por documento (sacamos nombre y apellido?)... pero en el caso que luego de filtrar sea vació y el factor de búsqueda sean al menos 8 caracteres, vaya a buscar los datos a otros sistemas, carga el paciente y lo devuelve. solo faltaría el orden de búsqueda en los sistemas e implementar el nuevo q dijo Belen
