### ISSUE TITLE
Interfaz para carga de Consulta

### ISSUE THREAD

**Issue by mgaitan** [cluster311/ggg#27]
depende de #25 y #26 

Esta es la interfaz para el profesional. 

Templates base basado en bs4 (mismo de tableros) 

- ListView que muestra fecha - especialidad y profesional de la consulta, es lo que puede ver el médico. la url 

url: `/paciente/<dni>/historia`

- createview/updateview con un formulario para crear consultas.

Tiene que tener un campo que permite asociar los códigos cie10. Ver #26

- UpdateView idem vista anterior.

**Comment by wilmays10** [comment]
@mgaitan tengo casi listo esto. Sólo me resta un detalle, que no está aclarado inicialmente.
¿Cuál sería la página principal? Es decir, lo primero que ve el profesional. Se me había ocurrido hacer un buscador, basado en django-autocomplete-light, para que se ingrese el número del dni y ahí recién redirigir a la historia clínica. Pero tal vez sea para desarrollarlo en otro issue. ¿Qué decís?

**Comment by mgaitan** [comment]
basicamente el médico ya deberia poder acceder a la historia clinica del paciente porque tiene que ver quien es el turno. 

hagamos otro ticket yo creo que amerita un pequeño dashboard. donde ve la lista de pacientes con turnos confirmados y le aparece en grande el que debe llamar. 

@ryacyna podes aportar algo acá?

**Comment by ryacyna** [comment]
Cuando se ingresa a ver el calendario de los días disponibles se ve el mes
completo.
O sea uno selecciona el mes y ahí ya tendría que estar definido los días
según el servicio.
