### ISSUE TITLE
Agregar tipo_beneficiario y parentesco al Anexo2

### ISSUE THREAD

**Issue by marcorichetta** [cluster311/ggg#274]
Los campos `tipo_beneficiario` y `parentesco` hacen referencia a la relación del Paciente con las Obras Sociales a las que está afiliado. Estos campos fueron agregados en #267.

**Problema**
Estos datos deben ser sacados de la relación **ObraSocial <=> Paciente** pero el Anexo2 los busca dentro 
de los datos del paciente.

**Solucion propuesta**
Sacar del [esquema de validación del Anexo2](https://github.com/cluster311/Anexo2/blob/b47259d53e88abaff34ea6eefa77ae7bb61e2d31/anexo2/docs.py#L102) los campos `tipo_beneficiario` y `parentesco` de la sección **beneficiario** y colocarlos dentro de **obra_social**
```diff
'beneficiario': {
    'type': 'dict',
    'schema': {
-        'tipo_beneficiario': 
-        'parentesco':
    }
}
...
'obra_social': {
    'type': 'dict',
    'schema': {
+        'tipo_beneficiario':
+        'parentesco':
    }
}
```

 - [ ] Agregar los campos al método `as_anexo2_json` del [modelo ObraSocialPaciente](https://github.com/cluster311/ggg/blob/54acf06920b3c242c09d4c4ee730c639a22839c3/obras_sociales/models.py#L95)

**Comment by marcorichetta** [comment]
Otra _solución_ sería hacer algo como esto antes de mandar los datos para que se genere el Anexo2
```py
beneficiario['tipo_beneficiario'] = obra_social['tipo_beneficiario'] 
beneficiario['parentesco'] = obra_social['parentesco'] 
```

@avdata99 @ramosfm Necesitaría su opinión para ver si hay una mejor forma.

**Comment by avdata99** [comment]
> Otra _solución_ sería hacer algo como esto antes de mandar los datos para que se genere el Anexo2
> 
> ```python
> beneficiario['tipo_beneficiario'] = obra_social['tipo_beneficiario'] 
> beneficiario['parentesco'] = obra_social['parentesco'] 
> ```
> 
> @avdata99 @ramosfm Necesitaría su opinión para ver si hay una mejor forma.

@marcorichetta, la librerìa Anexo 2 creo que esta pidiendo los datos de una manera razonable.
Nuestros modelos no necesitar calzar exacto con eso.

Tu segunda propuesta me parece màs razonable. Hacer funciones en nuestra app que estructuren los datos en la forma quen es necesaria para Anexo 2.

Quizas esas funciones `as_anexo_2` no son aplicables modelo a modelo y necesitemos algo mas integrador en una sola funcion.
Tu segunda solucion se aproxima mas a lo que hay que hacer. En este caso no hay que tocar la librería anexo 2, tenemos que adaptar las funciones de GGG para que entreguen los datos como se esperan

**Comment by marcorichetta** [comment]
@avdata99 Me queda más claro y lo voy a tener en cuenta para futuras modificaciones de Anexo2.
Gracias por la respuesta Andrés.
