### ISSUE TITLE
Interfaz para generacion de agenda de servicio

### ISSUE THREAD

**Issue by mgaitan** [cluster311/ggg#28]
basado en calendario, necesitamos una vista para admistracion que permita generar y editar turnos para el servicio. 

 - [x] form inicio, fin, duracion (esto es una propiedad del servicio que el administrativo puede modificar), profesional  donde profesional es uno de los afectados al servicio. 
 - [ ] debe tener boton "copiar de semana anterior" 
 - [ ] se pueden borrar o modificar turnos clickeando. abre un cuadro modal 
 - [x] Agregar estados para los turnos. Disponible (por atender), cancelado por el usuario, cancelado por el establecimiento, asignado, atendido.

**Comment by avdata99** [comment]
relacionado a #61

**Comment by avdata99** [comment]
Quedo en Review esto @mgaitan 
Quizas tengas algun detalle para pasar y cerrarlo o seguirlo en #61

**Comment by mgaitan** [comment]
@avdata99 no está hecho esto? que falta?

**Comment by avdata99** [comment]
Te lo pasé a lista al ticket. Lo que no está tildado no existe aún

**Comment by avdata99** [comment]
Se creo #93 para la copia de turnos
El modal ya esta cubierto en #74
