### ISSUE TITLE
Confirmación de turno

### ISSUE THREAD

**Issue by mgaitan** [cluster311/ggg#30]
Cuando un paciente se presenta por mesa de entrada en horario, le recepcionista confirma el turno. Hace falta una interfaz rapida para esto, ingresando numero de dni de paciente. 
Debe haber una vista administrativa donde el usuario que tiene permiso de ver turnos puede ver todos los turnos del día (con un color diferente por estado).

Con un click en cada elemento del turno puede realizar diferentes acciones (revisar los estados que están y validar con @ryacyna):
 - [x] Llego el paciente (cambia al estado confirmado)
 - [ ] Paciente fue atendido (lo carga el profesional en #97)
 - [x] Cancelar turno
 - [ ] Agregar sobreturno (se resuelve en #31)

depende de #28

Ese turno pasaria al estado "Esperando en sala"
(Ver estados disponibles en el sistema actual
![Asignar turno](https://user-images.githubusercontent.com/28638853/66875302-32e37600-ef84-11e9-84db-277abf9becef.jpeg)
)

**Comment by avdata99** [comment]
Error al cancelar turno. Supongo que ya lo tenes
```
{
  "success": false, 
  "errors": {
    "paciente": "El turno deberia tener un paciente asignado"
    }
}
```
![image](https://user-images.githubusercontent.com/3237309/68985079-afbb7700-07f2-11ea-8fe7-5bff0f4f9cf7.png)
