### ISSUE TITLE
[BUG] API SSS devuelve un tipo de documento incompatible con el Anexo2

### ISSUE THREAD

**Issue by marcorichetta** [cluster311/ggg#306]
### Problema
- Cuando se crea un paciente mediante la librería [SSS](https://github.com/cluster311/sss-beneficiarios), al paciente se le asigna `tipo_documento = "DOCUMENTO UNICO"`. [Source](https://github.com/cluster311/sss-beneficiarios/blob/bc55c916f69792b8a3518ee4ab7d734016b018bd/tests/test_base.py#L22)

- Esto hace que falle la generación del Anexo2, que espera que `tipo_dni` sea "DNI | LE | LC". [Source](https://github.com/cluster311/Anexo2/blob/4c56bcdf51428bb5488b48a5875e4c9904b1aab6/anexo2/docs.py#L119)

- Además el modelo `Persona` no tiene la opción `DOCUMENTO UNICO` el campo `tipo_documento` [Source](https://github.com/cluster311/ggg/blob/0908facdef68e07c75f712363aac4f93e53ab4a5/core/models.py#L58)

**Como reproducir el error**
1. Generar una factura ingresando un DNI nuevo para que se cree el paciente mediante la función [`create_from_sss()`](https://github.com/cluster311/ggg/blob/b8ee79e0454b60e80c25a66028d684fb6b5ceff5/pacientes/models.py#L181)
2. Intentar generar el Anexo2.

![imagen](https://user-images.githubusercontent.com/19599150/92659803-76974a80-f2cf-11ea-9a97-968650903e3d.png)

### Ideas
 - Cambiar el esquema de Anexo2 para que acepte el valor "DOCUMENTO UNICO"
   - Además hay que agregar ese valor como una opción en el modelo `Persona`
 - La otra es sobreescribir el valor obtenido por SSS para que no tenga problemas con el Anexo2.
   - "DOCUMENTO UNICO" => "DNI"

**Comment by avdata99** [comment]
Antes de ir al anexto 2 hay que corregir los datos para que encaje @marcorichetta 
Creo que la mejor solucion es con las funciones `as_anexo_2` (o funciones similares). Son datos distintos y esta bien que sean distintos pero antes de imprimi el anexo 2, debe adaptarse a el

**Comment by avdata99** [comment]
Quizas tambien haya que estandarizar al momento de agregar el paciente para coincidir datos de SISA/PUCO y de SSS @marcorichetta
