### ISSUE TITLE
Sacar JET

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#44]
- [x] Sacar JET
- [x] Ver como queda _Address_. Compartir por slack alguna imagen si quedan dudas de seguir o no usándolo
- [x] Si se mata Address proponer un reemplazo
  - [x] Analizar [Django cities light](https://github.com/coderholic/django-cities)
  - [ ] Dejar un ticket hecho para validar los códigos de provincia con los de SSSalud y SISA (Secretaría de Salud)

**Comment by mgaitan** [comment]
los codigos de provincia y sisa cuales son? los tenemos ya modelados?

**Comment by avdata99** [comment]
Se refiere a los codigos o nombres de provincias que usan las librerías anexas, cada una tiene las provincias distinto. Por ejemplo la base de obras sociales tiene solo nombres e incluye una no-provincia que es nacion y algunas son _None_.
Necesitamos que Address sea flexible, despues podemos mergear las provincias

**Comment by wilmays10** [comment]
Address permite optar entre tus datos o dejar el que encuentra a través del api de Google.

**Comment by avdata99** [comment]
Pero hay provincias inexistentes. Necesitamos direcciones inválidas @wilmays10 
Si es así, dale nomas.
Tenes para probar los importadores de profesionales y el de obras sociales.
No demos muchas vueltas, lo ideal es que ande pero no nos puede trabar mucho esto

**Comment by avdata99** [comment]
Tambien podría tener una direccion, ciudad y provincia como string y opcionalmente una direccion real en casos en que se detecte correctamente

**Comment by wilmays10** [comment]
Compartiste por algún lado los archivos para importar los datos @avdata99? yo no los tengo..

**Comment by avdata99** [comment]
Van x slack @wilmays10
