### ISSUE TITLE
Revisar modelos de servicios/especialidades

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#46]
- [ ] Renombrar los modelos de especialidades como _servicios_
- [ ] Agregar un campo que sea _es_especialidad_
- [ ] Importar la lista de servicios (andrés la pide)
- [ ] Agregar una propiedad tiempo_predeterminado_turno para usar en la creación de turnos.

**Comment by wilmays10** [comment]
@avdata99 a ver si entendí bien: la tabla actual que se llama servicio la borramos y la tabla especialidad pasa a ser servicio? 
De dónde saco la lista de servicios?

**Comment by avdata99** [comment]
No tenemos lista de servicios. Usa una temporal que tenga los valores que quieras por ahora.
Creo que habíamos hablado de renombrarla y agregarle un campo. No necesariamente borrarla.
Como en produccion no tenemos la base definitiva entonces se podría borrar si es necesario @wilmays10

**Comment by avdata99** [comment]
Pasado a milestone _Nice to have_
 - No hay lista de servicios ni especialdiades disponibles para cargar
 - Ya se definicio la relacion entre servicios y especialidades (validar)
 - [No se consigió](https://github.com/cluster311/ggg/blob/master/calendario/static/calendario/js/consulta-form.js#L16-L17) setear los minutos como atributos de los servicios
