### ISSUE TITLE
Manuales

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#5]
Literal según doc
```
 - Entrega de Manual de procedimientos de uso de la plataforma (general)
```

- [x] Iniciar un Google Drive con los básico de CIE10, Centros de Salud y profesionales (@ryacyna) 
- [x] Compartir link así todos aportamos y sumamos al equipo municipal

**Comment by mgaitan** [comment]
Vamos a usar un drive. @ryacyna pegá el link acá asi se lo compartimos tambien a Alejandra

**Comment by avdata99** [comment]
Link al manual
https://docs.google.com/document/d/1ePgRHtQiG81u2eF4qf48ozq4RMyviwgu/edit

PDF en tiempo real
https://docs.google.com/document/d/1ePgRHtQiG81u2eF4qf48ozq4RMyviwgu/export?format=pdf
