### ISSUE TITLE
Corregir nueva consulta

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#51]
Los profesionales deben elegirse autocompletando, es muy pesado
![image](https://user-images.githubusercontent.com/3237309/67254460-8279e400-f453-11e9-947b-53aa1172dd2d.png)

El código CIE10 debe estar más arriba y elegirse también por la descripción, no sólo código
![image](https://user-images.githubusercontent.com/3237309/67254492-b3f2af80-f453-11e9-9f69-2ca3b8c4b72a.png)

**Comment by mgaitan** [comment]
por qué salen como tuplas los nombres de los profesionales?

**Comment by wilmays10** [comment]
Los nombres de los profesionales se veían como tuplas porque estaba mal el __str__
Igual, hay que corregir el importador de datos porque en los datos vienen nombre y apellido en un sólo campo y en el modelo los tenemos separados.
