### ISSUE TITLE
Home del sistema

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#55]
Según #52   El usuario administrativo del municipio tiene una URL donde iniciar en un sitio identificado con un nombre/logo preferentemente diferente al admin de django o al menos una version diferenciada

**Comment by mgaitan** [comment]
usemos una app. puede ser https://django-allauth.readthedocs.io  y de paso queda facil integrar cualquier login oauth2 de terceros como un plugin de eso. 
tiene todo el flujo de password recovery y demás. 

alternativa es https://github.com/pinax/django-user-accounts

**Comment by avdata99** [comment]
Implementé allccounts hace poco en otro proyecto y anda OK. En este caso los usuarios esperados son empleados de gobierno posiblemente sin gmail u otras plataformas similares. Si se permite el registro comun vía email. Sirve.
Voy a analizar eso
