### ISSUE TITLE
Mejoras generales Turnos

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#61]
**Agregar nuevos issues si es necesario.**

Relevamiento del equipo municipal sobre la generación de turnos:
 - Al generar calendario de turnos:
   - [x] no necesito el selector de pacientes. No es el momento, eso se asigna de a uno despues
   - [x] no necesito el estado (es siempre disponible)
   - [ ] La lista de profesionales es pesada. Debe ser un buscador, no se debe cargar completa
   - [x] Conectar servicios a profesionales (en algún lugar del backend) para que cuando se elija un servicio esta lista pueda filtrarse. Hoy podemos poner a un pediatra a atender servicios de ginecología
   - [ ] revisar los permisos del usuario (todavía no definidos, ver #45) para que solo se muestren los servicios de los centros de salud sobre los que tiene permisos. Esto va a agilizar el formulario también.
   - [x] Revisar los horarios de los turnos. ¿Está validado que si defino tuirnos desde un lunes a las 7 AM hasta el viernes a las 14 hs no me llena las 24 hs? ¿Como defino hora de inicio y fin de cada día?
   - [ ] Si quiero definir 15 días seguidos ¿como hago para anular los sábados y domingos de la lista?
   - [ ] ¿Como descarto los feriados que quedan dentro de una selección?

Otras tareas:
 - [ ] Definir una URL/menú para ver el calendario de turnos agendado. 
   - [ ] Agregar filtro por centro de salud y servicio
 - [ ] URL/Menú para que personal administrativo asigne un turno ya generado a un paciente
 - [ ] Definir vista para usuarios de tipo ciudadano. Para elegir un turno y asignarselo. Recordar que una persona puede definir personas para otras (sus hijos por ejemplo)

Te sumo acá Rene porque vos podes validar detalles

**Comment by wilmays10** [comment]
>  La lista de profesionales es pesada. Debe ser un buscador, no se debe cargar completa

Pueden usar esto que hice [acá](https://github.com/cluster311/ggg/blob/master/core/views.py#L49).
Y acá está el [form](https://github.com/cluster311/ggg/blob/master/pacientes/forms.py#L21) que usa el autocompletado.



> Conectar servicios a profesionales (en algún lugar del backend) para que cuando se elija un servicio esta lista pueda filtrarse. Hoy podemos poner a un pediatra a atender servicios de ginecología

Creo que lo voy a resolver en este [ticket](https://github.com/cluster311/ggg/issues/46)
