### ISSUE TITLE
En las consultas permitir permitir agregar dinamicamente inlines

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#72]
Al crear una consulta las recetas, derivaciones y prestaciones deberían tener un boton _agregar_ para que esto sea dinámico y no tener que dejar fija la cantidad

Aca se explica:
https://medium.com/all-about-django/adding-forms-dynamically-to-a-django-formset-375f1090c2b0

**Comment by avdata99** [comment]
Para seguir despues de #73

**Comment by mgaitan** [comment]
hago esto @avdata99
