### ISSUE TITLE
No se pueden grabar las consultas

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#73]
En _/profesionales/paciente/nueva-consulta_ no anda grabar.

Por más que se cargan los datos estos se pierden y no funciona

![image](https://user-images.githubusercontent.com/3237309/68265288-6026bf80-002a-11ea-9051-aa9dea481bbb.png)

**Comment by mgaitan** [comment]
lo puedo agarrar yo

**Comment by wilmays10** [comment]
@mgaitan bueno

**Comment by mgaitan** [comment]
arranco esto
