### ISSUE TITLE
Home ciudadanos

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#78]
En la url _/ciudadano_ disponer la home del sitio para el ciudadano
Así como hay un template base para la administración del sistema necesitamos uno para los ciudadanos.

Esta URL debe (como en la home administrativa) dar la posibilidad de registrarse o loguearse. Nada más.
Este es el HTML de la home administrativa: https://github.com/cluster311/ggg/blob/master/ggg/templates/home.html#L1

El template a usar aquí puede ser el mismo de la parte administrativa pero si es así, debe ser otro color (por ejemplo lo mismo pero en tonos de verde). Tambien se podría usar otro template.
Tener en cuenta que el sitio del ciudadano le va a permitir sacar turnos y hacer otros trámites. Va a tener un perfil de sistema administrativo tambien

**Comment by mgaitan** [comment]
hago esto

**Comment by avdata99** [comment]
Ya lo estaba haciendo @alantoris creo @mgaitan

**Comment by avdata99** [comment]
Mira este PR @alantoris: https://github.com/cluster311/ggg/pull/90
Martían avanzo con esto. Fijate como lo mezclas con lo que estabas haciendo y preguntá cualquier cosa
