### ISSUE TITLE
Mis turnos

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#80]
En la home del ciudadano agregar una sección llama _mis turnos_ donde aparezcan los turnos que ya tengo confirmados.
En esta lista cada elemento puede tener una opción _cancelar_ para cuando el ciudadano quiere cancelar un turno.
La lista debe incluir el DNI/nombre del paciente (puede no ser el mismo que el ciudadano que lo sacó), servicio, profesional, fecha, hora y centro de salud

**Comment by avdata99** [comment]
Depende de #29

**Comment by alantoris** [comment]
@avdata99 deberian aparecer los turnos que un usuario solicito para un tercero? o solo los que se solicitaron con el dni del ciudadano logeado? porque ahora solo se esta guardando la referencia al paciente que va a ser atendido (el que se ingresa el dni), no al usuario que reservo el turno.

**Comment by avdata99** [comment]
Buen punto @alantoris. Agrega un campo no requerido que sea el usuario que hace la solicitud (y puede ser distinto al paciente)
De esta forma, al ciudadano le mostramos sus turnos y los que saco para otros en su perfil (podríamos mostrarlos con algún color distinto o algo así)

**Comment by alantoris** [comment]
Perfecto @avdata99 , esa relacion seria con el modelo User no? o con Paciente tambien?

**Comment by avdata99** [comment]
Efectivamente @alantoris, el que registra el turno es modelo _User_, el que será atendido es un _Paciente_. Son dos campos referidos a clases distintas. El User que registra el turno podría no ser paciente todavía (salvo que cada vez que se cree un usuario lo convertimo en paciente, cosa que creo que no pasa y esta bien que sea así)

**Comment by mgaitan** [comment]
esto se puede cerrar?
